### ISSUE TITLE
Navigation buttons stopped working

### ISSUE THREAD

**Issue by themaxw** [matthiasemde/musikus-android#132]
hey, since 3 nightlies ago (v0.10.0-nightly2436700) i can't use the navigation buttons on the bottom of the screen to switch between sessions, goals, statistics and library anymore.

When i click a button, it reacts to the click with a little grey round rectangle flashing softly behind it, but nothing happens after that.

**Comment by matthiasemde** [comment]
Hi @themaxw,
Thanks for bringing it to our attention. We definitely need more integration tests 😀

I've already found the issue and am preparing a fix!

**Comment by themaxw** [comment]
thanks for fixing it :)

**Comment by matthiasemde** [comment]
You're welcome. Sorry it took so long 😅
